Jazzar/juniper
appsembler/sultan pull request #22
Opened 2020-10-21 18:51 UTC by ahmedaljazzar

2020-11-03 16:44 UTC, thraxil commented
My first attempt with a clean checkout and following the quickstart instructions in the README:

```
$ ./sultan config init
./sultan: 6: source: not found
./sultan: 7: source: not found
./sultan: 29: Syntax error: Bad function name
```

`/bin/sh` on Ubuntu is actually `dash`, which doesn't support `source`. Unless we are trying to support some ancient version of AIX or something, we are probably better off explicitly using `/bin/bash` for all the scripts.

Documentation-wise, I'd suggest continuing the quickstart all the way through to getting a running devstack. As it is, a new user following the instructions gets their config created, then the documentation veers off into discussions of various other possible setups and advanced options that they might want. They have to then read through all of that to eventually figure out that `sultan instance setup` comes next.

I haven't investigated why yet, but it's also a bit annoying that it doesn't seem to be able to pick up on my running `ssh-agent`. I get prompted for the passphrase for my ssh key about half a dozen times during the process.

2020-11-03 16:46 UTC, thraxil requested changes

2020-11-03 16:46 UTC, thraxil commented on scripts/configurations.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2020-11-03 16:46 UTC, thraxil commented on scripts/devstack.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2020-11-03 16:46 UTC, thraxil commented on scripts/firewall.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2020-11-03 16:46 UTC, thraxil commented on scripts/image.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2020-11-03 16:46 UTC, thraxil commented on scripts/instance.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2020-11-03 16:46 UTC, thraxil commented on scripts/local.sh
> +#!/bin/sh
```suggestion
#!/bin/bash
```

2020-11-03 20:21 UTC, ahmedaljazzar commented
Thanks @thraxil for the review. I just applied the changes you requested and tested them. I'll be looking into the ssh key issue you had.

2020-11-04 10:11 UTC, thraxil approved these changes

2020-11-05 09:16 UTC, ahmedaljazzar commented
Merging and will continue updating in separate PRs

2020-11-05 09:17 UTC, merged